BarterApp/BarterApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ads.urls', namespace='main')),
    path('accounts/', include('user.urls', namespace='user')),
    path('admin/', admin.site.urls),
]

BarterApp/ads/urls.py
from django.urls import path

from .views import (main_page,
                    create_ad,
                    ad_page,
                    rm_ad,
                    update_ad,
                    create_trade,
                    trade_page,
                    update_trade_status)

app_name = 'main'

urlpatterns = [
    path('',
         view=main_page,
         name='index'),
    path('<int:id>/',
         view=ad_page,
         name='detail'),
    path('createad/',
         view=create_ad,
         name='createform'),
    path('delete/<int:id>/',
         view=rm_ad,
         name='delete_ad'),
    path('update/<int:id>/',
         view=update_ad,
         name='update_ad'),
    path('<int:id>/createtrade/',
         view=create_trade,
         name='create_trade'),
    path('trades/',
         view=trade_page,
         name='trade'),
    path('<int:id>/updatetrade/',
         view=update_trade_status,
         name='update_trade')
]

BarterApp/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register

app_name = 'user'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='auth/login.html'),
         name='login'),
    path('register/', register, name='register'),
]

BarterApp/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>BarterApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">BarterApp</a>
        <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:createform' %}">Новое объявление</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:trade' %}">Трейды</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'user:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'user:register' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>